# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pulsepoint',
                'doc_host': 'https://cooper-richason.github.io',
                'git_url': 'https://github.com/cooper-richason/pulsepoint',
                'lib_path': 'pulsepoint'},
  'syms': {'pulsepoint.core': {'pulsepoint.core.foo': ('core.html#foo', 'pulsepoint/core.py')}}}
